### ISSUE TITLE
Ti ringrazio!

### ISSUE THREAD

**Issue by skrtdev** [condonato/LimitatiMakerRobot#1]
Grazie di cuore, prima di leggere il codice di questo bot ero stitico, ora sono completamente guarito! Grazie!

**Comment by cerberodocile** [comment]
Concordo con @skrtdev il codice mi fa vomitare ma certamente mi passerà e starò meglio. io non cambierei linguaggio di programmazione o editor ma cambierei direttamente il ""programmatore""

**Comment by skrtdev** [comment]
Ma no dai!

**Comment by skrtdev** [comment]
Che brutta cosa l'ignoranza

**Comment by cerberodocile** [comment]
Che brutta cosa fare e vendere code di merda...

**Comment by skrtdev** [comment]
@cerberodocile perchè hai cancellato l'account?

**Comment by cerberodocile** [comment]
> @cerberodocile perchè hai cancellato l'account?

Cuz ho quittato
